### PR TITLE
feat: Add frontend

### PR DESCRIPTION
**Pull request by fbufler**
This PR adds the frontend to the open source yaku repository.

### CODE REVIEW

**Review by frank-bee — APPROVED** [review]

**Review by frank-bee — CHANGES_REQUESTED** [review]
looks great, let me fix the licenses headers real quick

**Comment by frank-bee** [comment]
@fbufler I fixed the license headers and also some biome findings ( linter ) . Could you check real quick if the UI works still fine and merge?

**Comment by frank-bee** [comment]
@fbufler or let me add a workflow for the UI as well, not?

**Comment by fbufler** [comment]
@frank-bee still works, I've cleaned up the history again.
But in order to merge I still need your approval.

**Comment by fbufler** [comment]
> @fbufler or let me add a workflow for the UI as well, not?

Let's do it in a separate PR please, this one is already getting out of hands

**Review by frank-bee — APPROVED** [review]

**Pull request merged**
